

-- Usar el esquema
ALTER SESSION SET CURRENT_SCHEMA = vdsj;

-- Crear la tabla de usuarios
CREATE TABLE usuario1 (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR2(50) NOT NULL,
    password VARCHAR2(50) NOT NULL
);

-- Insertar un usuario de prueba
INSERT INTO usuario1 (usuario, password) VALUES ('admin', '1234');

-- Confirmar cambios
COMMIT;

-- Verificar que quedó bien
SELECT * FROM usuario1;
SELECT * FROM operacion;


CREATE TABLE operacion (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operacion VARCHAR2(50) NOT NULL,
    importe NUMBER(10,2) NOT NULL,
    cliente VARCHAR2(100) NOT NULL,
    referencia VARCHAR2(6),
    estatus VARCHAR2(20),
    secreto VARCHAR2(255)
);
